server:
  port: 9000

encryption:
  key-store:
    alias: mytest
    location: file:/Users/olusoji/IdeaProjects/oauth2-server/keystore.jks
    classpath-loc: keystore.jks
    password: mypass
    secret: mypass
core:
  service:
    db:
      password:
      username: sa
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true